[phases.setup]
aptPkgs = ["tesseract-ocr", "libtesseract-dev"]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
